spring:
  ai:
    mcp:
      server:
        version: 0.0.1
        stdio: false # disabled for streamable mode
        protocol: STREAMABLE
        type: SYNC
        streamable-http:
          mcp-endpoint: /mcp
        annotation-scanner:
          enabled: true
  main:
    banner-mode: "off"
    web-application-type: servlet # enabled for streamable mode
  application:
    name: mvno-mcp-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-poc.onwavemaker.com/realms/AiIntegration

server:
  port: 8080


logging:
  console:
    enabled: true # enabled for streamable mode
  level:
    root: INFO
  file:
    name: ${user.home}/logs/mvno-mcp-server/mnvo-mcp-server.log
